#!/usr/bin/env python3
import sys, os

sys.path.insert(0, os.path.join(os.path.dirname(sys.argv[0]), 'lib'))

from fbuild.main import main

# don't know why someone would need this...but oh well
if __name__ == '__main__':
    main()
