#!/usr/bin/env python3.0

import os
import sys
import imp

fbuild_dirname = os.path.dirname(sys.argv[0])
env = dict(os.environ)
env['PYTHONPATH'] = env.get('PYTHONPATH', '') + ':' + \
    os.path.join(fbuild_dirname, 'lib')

sys.exit(os.execve(sys.executable,
    [sys.executable,
    os.path.join(fbuild_dirname, 'bin', 'fbuild')] +
    sys.argv[1:],
    env))
